<?php

namespace ContainerGfqJNUI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExercisesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ExercisesController' shared autowired service.
     *
     * @return \App\Controller\ExercisesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ExercisesController.php';

        return $container->services['App\\Controller\\ExercisesController'] = new \App\Controller\ExercisesController(($container->services['App\\Repository\\ExercisesRepository'] ?? $container->load('getExercisesRepositoryService')));
    }
}
