<?php

namespace ContainerGfqJNUI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtCreatedSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Events\JwtCreatedSubscriber' shared autowired service.
     *
     * @return \App\Events\JwtCreatedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/JwtCreatedSubscriber.php';

        return $container->services['App\\Events\\JwtCreatedSubscriber'] = new \App\Events\JwtCreatedSubscriber();
    }
}
